var animDelay = 150
var questions = [
    "Who is your best girl friend?",
    "Who is your best guy friend?",
    "What famous person, alive or dead, would you want to invite to a dinner party?",
    "What is your age?",
    "Who was the last person you texted?",
    "If you've sold your soul to the devil, what did he give you for it? ",
    "Name your number-one crush. ",
    "Name one random fact about you. ",
    "If you could know the real truth behind any mystery or secret in the world, which would it be? ",
    "Have you ever fallen in love?",
    "Are you single or taken?",
    "If you could go back in time and witness one historical event, what would it be? ",
    "What is your favorite food?",
    "What is your favorite quote?",
    "Who was your first kiss?",
    "If you could time travel, would you rather go forward or backward?",
    "What are you most addicted to?",
    "Have you ever smoked?",
    "If you could uninvent one thing, what invention would you go back in time and erase from history? ",
    "What is your favorite song?",
    "What is your favorite animal?",
    "If you could have one wish, what would it be?",
    "What's your secret obsession?",
    "How long was your longest romantic relationship?",
    "What's your biggest pet peeve? ",
    "If you could be haunted by anyone, who would it be?",
    "What was the best time of your life? ",
    "Describe the last time you gave someone a second chance. ",
    "If you were a powerful lawmaker, what law would you abolish? ",
    "Name the countries you've visited. ",
    "What was your favorite subject in school? ",
    "What are you most insecure about?",
    "Who do you miss?",
    "What's the last song you listened to on purpose?",
    "What's your favorite sport to play?",
    "What's your dream job?",
    "Do you prefer daytime or nighttime? ",
    "Describe the perfect date. ",
    "What's the last thing you sang in the shower?",
    "What's your favorite color?",
    "Name your favorite movie. ",
    "Describe your current mood. ",
    "You're stranded on an island. Could you survive with just the things you have with you? ",
    "What is your biggest fear? ",
    "What is something that you hate?",
    "What is your star sign?",
    "What is your favorite book?",
    "Describe your most embarrassing moment. ",
    "What is your most impressive secret talent?",
    "Describe your current love life in one word. ",
    "If you had to choose your own nickname, what would it be?",
    "Are you afraid of the dark?",
    "What's the number-one item on your bucket list?",
    "If your house was burning down and you could only save one material possession, what would it be? ",
    "Name something that upset you recently. ",
    "Describe your relationship with your parents. ",
    "What is your favorite holiday?",
    "Share a confession. ",
    "Name one thing you've lied about. ",
    "What is one thing that's constantly on your mind?",
    "Who is your biggest celebrity crush? ",
    "Do you believe in ghosts?",
    "Who made you mad recently?",
    "What's the worst thing someone could do for you?",
    "What is your favorite poem?",
    "On a scale of 1 to 10, how attractive do you think you are?",
    "What did you want to be when you were a child?",
    "Describe the best day of your life. ",
    "Describe the worst day of your life. ",
    "You'll love someone if they: ",
    "You'll dislike someone if they: ",
    "Name 3 of your most interesting habits. ",
    "How would you live differently if you were the only human in the world?",
    "What would you choose to do if absolutely nobody was going to judge you for it? ",
    "If you could instantly master any skill, what would it be?",
    "If you could be guaranteed that you'd get an honest answer to a question, who would you ask, and what would the question be? ",
    "You can pick three friends to help you survive the zombie apocalypse. Who would they be, and why?",
    "What is your favorite cartoon? ",
    "If you could be cryogenically frozen and woken up in 1,000 years, would you choose to do it?",
    "What product would you stockpile if you learned that they were about to stop producing it?",
    "If you could choose any superpower, what would it be?",
    "If you were extremely wealthy, what eccentricities and rich activities would you indulge in?"
]

function newQuestion() {
	$("#question").fadeOut(animDelay, () => {
		$("#question").html(questions[Math.floor(Math.random() * questions.length)])
	})
	$("#question").fadeIn(animDelay)
}

newQuestion()
